# Generated by Django 3.2.16 on 2023-01-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledgers', models.TextField()),
                ('authentication', models.CharField(max_length=64)),
            ],
        ),
    ]
