# Generated by Django 3.2.16 on 2023-01-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='id',
        ),
        migrations.AlterField(
            model_name='update',
            name='authentication',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
