# Generated by Django 3.2.16 on 2023-01-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0002_auto_20230125_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('contact_url', models.CharField(max_length=150)),
            ],
        ),
    ]
