# Generated by Django 3.2.16 on 2023-01-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0004_privateregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateRegister',
        ),
    ]
