# Generated by Django 3.2.16 on 2023-01-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0010_privateregister_update_volunteerusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateRegister',
        ),
    ]
