# Generated by Django 3.2.16 on 2023-01-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0011_delete_privateregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_hash', models.CharField(max_length=64)),
                ('password_hash', models.CharField(max_length=64)),
                ('lock', models.CharField(max_length=64)),
                ('register_time', models.FloatField()),
            ],
        ),
    ]
