# Generated by Django 3.2.16 on 2023-01-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0014_privateregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateRegister',
        ),
    ]
