# Generated by Django 3.2.16 on 2023-01-31 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0020_privateregister_update_volunteerusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateRegister',
        ),
    ]
