# Generated by Django 3.2.16 on 2023-01-31 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0022_privateregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateRegister',
        ),
    ]
