# Generated by Django 3.2.16 on 2023-02-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0034_privateregister_update_volunteerusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateRegister',
        ),
    ]
