# Generated by Django 3.2.16 on 2023-02-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0036_privateregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateRegister',
        ),
    ]
