# Generated by Django 3.2.16 on 2023-02-03 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0040_privateregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateRegister',
        ),
    ]
