# Generated by Django 3.2.16 on 2023-02-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0045_delete_privateregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateRegister',
            fields=[
                ('vid_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=64)),
                ('lock', models.CharField(max_length=64)),
                ('register_time', models.FloatField()),
            ],
        ),
    ]
