# Generated by Django 3.2.16 on 2023-02-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0047_trxshash'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx', models.CharField(max_length=2000)),
            ],
        ),
    ]
