# Generated by Django 3.2.16 on 2023-02-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0050_bookexchang'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookExchang',
        ),
    ]
