# Generated by Django 3.2.16 on 2023-02-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0055_bookpublish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('vid', models.IntegerField()),
                ('price', models.FloatField()),
                ('coin_reward', models.FloatField()),
                ('village_bank_interest', models.FloatField()),
            ],
        ),
    ]
