# Generated by Django 3.2.16 on 2023-02-06 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0058_delete_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Election',
        ),
    ]
