# Generated by Django 3.2.16 on 2023-02-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0059_delete_election'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_type', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=100)),
                ('idea_url', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=500)),
                ('vid', models.IntegerField()),
                ('price', models.FloatField(blank=True)),
                ('coin_reward', models.FloatField(blank=True)),
                ('village_bank_interest', models.FloatField(blank=True)),
            ],
        ),
    ]
