# Generated by Django 3.2.16 on 2023-02-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0060_election'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookExchange',
        ),
        migrations.DeleteModel(
            name='BookPublish',
        ),
        migrations.DeleteModel(
            name='BookTransaction',
        ),
        migrations.DeleteModel(
            name='CoinTransaction',
        ),
        migrations.DeleteModel(
            name='Election',
        ),
        migrations.DeleteModel(
            name='PrivateRegister',
        ),
        migrations.DeleteModel(
            name='TrxsHash',
        ),
        migrations.DeleteModel(
            name='Update',
        ),
        migrations.DeleteModel(
            name='VolunteerUsers',
        ),
    ]
