# Generated by Django 3.2.16 on 2023-02-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0062_bookexchange_bookpublish_booktransaction_cointransaction_election_privateregister_trxshash_update_vo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookPublish',
        ),
    ]
