# Generated by Django 3.2.16 on 2023-02-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0063_delete_bookpublish'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPublish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_publisher_id', models.IntegerField()),
                ('book_title', models.CharField(max_length=30)),
                ('book_text', models.CharField(max_length=500)),
                ('book_cover_url', models.CharField(max_length=500)),
                ('last_price', models.FloatField(blank=True, default=0.0)),
                ('owner_id', models.IntegerField(blank=True, default=-1)),
                ('instagram_url', models.CharField(blank=True, max_length=500)),
                ('wiki_url', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
