# Generated by Django 3.2.16 on 2023-02-19 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0064_bookpublish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Election',
        ),
    ]
