# Generated by Django 3.2.16 on 2023-02-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0070_delete_election'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('idea_type', models.CharField(max_length=100)),
                ('text', models.CharField(blank=True, max_length=500)),
                ('idea_data', models.TextField()),
                ('like', models.IntegerField(default=0)),
            ],
        ),
    ]
