# Generated by Django 3.2.16 on 2023-02-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0071_election'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Election',
        ),
    ]
