# Generated by Django 3.2.16 on 2023-02-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0077_privateregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateRegister',
        ),
    ]
