# Generated by Django 3.2.16 on 2023-02-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0080_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
