# Generated by Django 3.2.16 on 2023-02-25 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0086_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteerusers',
            old_name='username',
            new_name='text',
        ),
    ]
