# Generated by Django 3.2.16 on 2023-02-27 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0088_rename_inestagram_url_volunteerusers_instagram_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookExchange',
        ),
        migrations.DeleteModel(
            name='BookPublish',
        ),
        migrations.DeleteModel(
            name='BookTransaction',
        ),
        migrations.DeleteModel(
            name='CoinTransaction',
        ),
        migrations.DeleteModel(
            name='Election',
        ),
        migrations.DeleteModel(
            name='PrivateRegister',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='TrxsHash',
        ),
        migrations.DeleteModel(
            name='Update',
        ),
        migrations.DeleteModel(
            name='VolunteerUsers',
        ),
    ]
