# Generated by Django 3.2.16 on 2023-02-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('neighbors', '0089_auto_20230227_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=150)),
                ('user_id', models.IntegerField()),
                ('proposed_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BookPublish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_publisher_id', models.IntegerField()),
                ('book_title', models.CharField(max_length=30)),
                ('book_text', models.CharField(max_length=500)),
                ('book_cover_url', models.CharField(max_length=500)),
                ('last_price', models.FloatField(blank=True, default=0.0)),
                ('owner_id', models.IntegerField(blank=True, default=-1)),
                ('instagram_url', models.CharField(blank=True, max_length=500)),
                ('wiki_url', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BookTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('idea_type', models.CharField(max_length=100)),
                ('text', models.CharField(blank=True, max_length=500)),
                ('idea_url', models.CharField(max_length=200)),
                ('idea_data', models.TextField()),
                ('like', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateRegister',
            fields=[
                ('vid_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=64)),
                ('lock', models.CharField(max_length=64)),
                ('register_time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('vb', models.IntegerField()),
                ('user_name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('image_url', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TrxsHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_hash', models.CharField(max_length=64)),
                ('trx_hash', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('ledgers', models.TextField()),
                ('authentication', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('instagram_url', models.CharField(max_length=1000)),
            ],
        ),
    ]
