# Generated by Django 3.2.16 on 2023-03-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0090_bookexchange_bookpublish_booktransaction_cointransaction_election_privateregister_profile_trxshash_u'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=20)),
                ('transaction', models.CharField(max_length=600)),
                ('transaction_signature', models.CharField(max_length=64)),
            ],
        ),
    ]
