# Generated by Django 3.2.16 on 2023-03-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0091_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_vb', models.IntegerField()),
                ('second_vb', models.IntegerField(blank=True)),
                ('notification_data', models.CharField(max_length=700)),
            ],
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
