# Generated by Django 3.2.16 on 2023-03-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbors', '0095_transactions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookExchange',
        ),
        migrations.DeleteModel(
            name='BookPublish',
        ),
        migrations.DeleteModel(
            name='BookTransaction',
        ),
        migrations.DeleteModel(
            name='CoinTransaction',
        ),
        migrations.DeleteModel(
            name='Election',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.DeleteModel(
            name='PrivateRegister',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
        migrations.DeleteModel(
            name='TrxsHash',
        ),
        migrations.DeleteModel(
            name='Update',
        ),
        migrations.DeleteModel(
            name='VolunteerUsers',
        ),
    ]
