# Generated by Django 3.2.16 on 2023-03-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('neighbors', '0096_auto_20230304_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('vb', models.IntegerField()),
                ('user_name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('image_url', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=20)),
                ('transaction', models.CharField(max_length=600)),
                ('transaction_signature', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TrxsHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_hash', models.CharField(max_length=64)),
                ('trx_hash', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('ledgers', models.TextField()),
                ('authentication', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('instagram_url', models.CharField(max_length=1000)),
            ],
        ),
    ]
