# Generated by Django 3.2.16 on 2023-03-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=20)),
                ('transaction', models.CharField(max_length=600)),
                ('transaction_signature', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionsHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vb_id', models.CharField(max_length=64)),
                ('trx_hash', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('ledgers', models.TextField()),
                ('authentication', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
    ]
